version: '3.9'

services:

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: "resourcedb"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "iFS3pbGm7LkF46Y"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d resourcedb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  service:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: "uwsgi --ini wsgi.ini"
    ports:
      - "3031:3031"
    depends_on:
      db:
        condition: service_healthy
  
